baseURL = '/'
languageCode = 'en-us'
title = 'Prof. Krampis Blog'
theme = "hugo-book"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]']]
          inline = [['$', '$']]

[params]
  BookTheme = 'dark'
  BookToC = true
  BookLogo = 'me.jpg'
  disablePathToLower = true
  enableGitInfo = true
  math = true
