baseURL = '/'
languageCode = 'en-us'
title = 'Solving AI Alignment'
theme = "hugo-theme-relearn"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['++++', '++++'], ['\[','\]'] ]
          inline = [['$','$'], ['latexmath:[',']']]

[security]
    [security.exec]
      allow = ['^(dart-)?sass(-embedded)?$', '^go$', '^npx$', '^postcss$', '^asciidoctor$']

[params]
  math = true
  themeVariant = ['zen-dark', 'zen-light']
  linkTitle = 'Solving AI Alignment'

  [params.logo]
    src = '/me-circle.png'
